#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Build All Installers
#based on: https://github.com/wiverson/maven-jpackage-template/blob/main/.github/workflows/maven-package.yml
#this is overly simplified and does not create working apps nor signed dmgs, etc
on:
  push:
    branches: [ main ]
  #  pull_request:
  #    branches: [ main ]
  #workflow_dispatch:
  #  branches: [ main ]
  #push:
   # tags:
    #  - 'v*' #push tags matching 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'#may need to move to liberica
          #java-package: jdk+fx -- not available with temurin
          cache: 'maven'
      - name: "Build with Maven"
        run: mvn -B clean install --file pom.xml
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            #tag_name: ${{ github.ref }}
            #release_name: Release ${{ github.ref }}
            tag_name: '${{ github.sha }}'
            release_name: 'Release ${{ github.sha }}'
            draft: true
            prerelease: true
      - name: Update Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ matrix.os }}
          prerelease: true
          draft: true
          title: ${{ matrix.os }} Development Build
          files: |
            ./tika-gui-app/target/*-bin.zip
